services:
  web:
    build: .
    volumes:
      - .:/app
      - sqlite_data:/app/data
      - media_data:/app/media
    ports:
      - "8002:8000"
    env_file:
      - .env

volumes:
  sqlite_data:
  media_data:
