# Generated by Django 4.2.25 on 2025-10-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilitybill',
            options={'ordering': ['-due_date']},
        ),
        migrations.RemoveField(
            model_name='utilitybill',
            name='meter_type',
        ),
        migrations.AlterField(
            model_name='metertype',
            name='reading_day_end',
            field=models.PositiveIntegerField(help_text='Day of month when reading period ends (1-31)'),
        ),
        migrations.AlterField(
            model_name='metertype',
            name='reading_day_start',
            field=models.PositiveIntegerField(help_text='Day of month when reading period starts (1-31)'),
        ),
        migrations.AlterField(
            model_name='metertype',
            name='unit',
            field=models.CharField(help_text='Unit of measurement (kWh, m³, etc.)', max_length=20),
        ),
    ]
