# Generated by Django 4.2.25 on 2025-10-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0002_alter_utilitybill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitybill',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Optional invoice number', max_length=100),
        ),
        migrations.AddField(
            model_name='utilitybill',
            name='paid_on',
            field=models.DateField(blank=True, help_text='Date when the bill was paid', null=True),
        ),
    ]
